"""
DataInsight API — Missing Values Router
=========================================
HTTP interface for missing-value detection and chart generation.

Endpoints:
    POST  /api/v1/missing-values/analyse/{dataset_id}
          Detect missing values, generate bar chart, return JSON + chart path.

    GET   /api/v1/missing-values/chart/{dataset_id}
          Download the pre-generated PNG chart for a dataset.

    GET   /api/v1/missing-values/summary/{dataset_id}
          Lightweight JSON-only summary (no chart generation).
"""

from __future__ import annotations

import pathlib

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse

from app.schemas.missing_values import MissingValuesReport, MissingValuesSummary
from app.schemas.response import SuccessResponse
from app.services.dataset_service import DatasetService
from app.services.missing_values_service import MissingValuesDetector, MissingValuesService
from app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(
    prefix="/missing-values",
    tags=["Missing Values Analysis"],
)


# ---------------------------------------------------------------------------
# Shared dependencies
# ---------------------------------------------------------------------------

def _get_dataset_service() -> DatasetService:
    """Retrieve the shared DatasetService from app.state."""
    from app.main import app
    return app.state.dataset_service


def _get_plots_dir() -> pathlib.Path:
    """Resolve the plots directory from the app's startup configuration."""
    from app.main import PLOTS_DIR
    return PLOTS_DIR


def _get_missing_values_service(
    service: DatasetService = Depends(_get_dataset_service),
    plots_dir: pathlib.Path = Depends(_get_plots_dir),
) -> MissingValuesService:
    """
    Construct a fresh MissingValuesService per request.

    Injecting both the DatasetService and plots directory keeps the router
    completely decoupled from filesystem paths and service construction.
    """
    return MissingValuesService(
        dataset_service=service,
        plots_dir=plots_dir,
    )


# ---------------------------------------------------------------------------
# Endpoint 1: Full analysis — JSON report + PNG chart
# ---------------------------------------------------------------------------

@router.post(
    "/analyse/{dataset_id}",
    response_model=SuccessResponse[MissingValuesReport],
    status_code=status.HTTP_200_OK,
    summary="Detect missing values and generate bar chart",
    description=(
        "Performs a comprehensive missing-values scan on every column and "
        "returns a structured JSON report alongside a Plotly bar chart "
        "saved as a PNG.\n\n"
        "**JSON report includes:**\n"
        "- Per-column: missing count, missing %, present count, dtype, severity\n"
        "- Dataset summary: total missing cells, overall %, severity-bucketed column lists\n"
        "- Chart metadata: file path, API download URL, dimensions, file size\n\n"
        "**Bar chart features:**\n"
        "- Horizontal bars, one per column, sorted by missing % (highest first)\n"
        "- Severity-coded colours: green (<5%) → amber (5–20%) → orange (20–50%) → red (>50%)\n"
        "- Annotated bars showing exact count and percentage\n"
        "- Reference lines at 5%, 20%, 50% thresholds\n"
        "- Dark-mode premium design, exported at 1400px wide\n\n"
        "Use `GET /missing-values/chart/{dataset_id}` to download the PNG."
    ),
    responses={
        200: {"description": "Analysis complete — JSON report and chart path returned"},
        404: {"description": "Dataset not found"},
    },
)
async def analyse_missing_values(
    dataset_id: str,
    svc: MissingValuesService = Depends(_get_missing_values_service),
) -> SuccessResponse[MissingValuesReport]:
    """
    Detect missing values across all columns and generate a bar chart.

    Args:
        dataset_id: UUID of the dataset to analyse.
        svc:        Injected MissingValuesService.

    Returns:
        SuccessResponse wrapping a MissingValuesReport with full stats
        and chart metadata (including PNG path and download URL).
    """
    logger.info("Missing values analyse request", dataset_id=dataset_id)

    report: MissingValuesReport = svc.analyse(
        dataset_id=dataset_id,
        api_base_url="/api/v1",
    )
    return SuccessResponse(data=report)


# ---------------------------------------------------------------------------
# Endpoint 2: Download the PNG chart
# ---------------------------------------------------------------------------

@router.get(
    "/chart/{dataset_id}",
    summary="Download the missing-values bar chart as PNG",
    description=(
        "Returns the PNG file generated by a previous call to "
        "`POST /missing-values/analyse/{dataset_id}`.  "
        "Raises HTTP 404 if the chart has not been generated yet for this dataset."
    ),
    responses={
        200: {"content": {"image/png": {}}, "description": "PNG chart file"},
        404: {"description": "Chart not found — run analyse first"},
    },
    response_class=FileResponse,
)
async def download_chart(
    dataset_id: str,
    plots_dir: pathlib.Path = Depends(_get_plots_dir),
) -> FileResponse:
    """
    Stream the pre-generated missing-values PNG chart to the client.

    Args:
        dataset_id: UUID of the dataset whose chart to retrieve.
        plots_dir:  Injected plots directory path.

    Returns:
        FileResponse streaming the PNG file.
    """
    chart_path = plots_dir / f"missing_values_{dataset_id}.png"

    if not chart_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"No chart found for dataset '{dataset_id}'. "
                "Run POST /missing-values/analyse/{dataset_id} first."
            ),
        )

    return FileResponse(
        path=str(chart_path),
        media_type="image/png",
        filename=f"missing_values_{dataset_id}.png",
    )


# ---------------------------------------------------------------------------
# Endpoint 3: Lightweight JSON summary (no chart)
# ---------------------------------------------------------------------------

@router.get(
    "/summary/{dataset_id}",
    response_model=SuccessResponse[dict],
    status_code=status.HTTP_200_OK,
    summary="Get missing-value summary without generating a chart",
    description=(
        "Returns a fast, lightweight missing-values summary for the dataset "
        "without building or exporting any chart. Ideal for dashboard widgets "
        "or quick health checks on data quality."
    ),
    responses={
        200: {"description": "Summary returned"},
        404: {"description": "Dataset not found"},
    },
)
async def get_missing_summary(
    dataset_id: str,
    service: DatasetService = Depends(_get_dataset_service),
) -> SuccessResponse[dict]:
    """
    Return a JSON-only missing-values summary (no chart generation).

    Args:
        dataset_id: UUID of the dataset to summarise.
        service:    Injected DatasetService.

    Returns:
        SuccessResponse with summary dict and per-column breakdown.
    """
    logger.info("Missing values summary request (no chart)", dataset_id=dataset_id)

    df = service.load_dataframe(dataset_id)
    detector = MissingValuesDetector()
    column_stats = detector.detect(df)
    summary = detector.build_summary(df, column_stats)

    return SuccessResponse(data={
        "dataset_id": dataset_id,
        "summary": summary.model_dump(),
        "columns": [c.model_dump() for c in column_stats],
    })
