"""
DataInsight API — Outlier Detection Router
==========================================
HTTP interface for the outlier detection engine.

Endpoints:
    POST  /api/v1/outliers/detect/{dataset_id}
          Run IQR / Z-Score / Isolation Forest detection, return JSON report + chart.

    GET   /api/v1/outliers/boxplots/{dataset_id}
          Download the pre-generated boxplot PNG chart.

    GET   /api/v1/outliers/methods
          List all registered detection strategies with parameters.

    POST  /api/v1/outliers/compare/{dataset_id}
          Run all three methods and compare their findings side-by-side.
"""

from __future__ import annotations

import pathlib

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import FileResponse

from app.schemas.outliers import (
    MethodCatalogEntry,
    OutlierDetectionReport,
    OutlierDetectionRequest,
    OutlierMethod,
)
from app.schemas.response import SuccessResponse
from app.services.dataset_service import DatasetService
from app.services.outlier_service import OutlierDetectionService
from app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(
    prefix="/outliers",
    tags=["Outlier Detection"],
)


# ---------------------------------------------------------------------------
# Shared dependencies
# ---------------------------------------------------------------------------

def _get_dataset_service() -> DatasetService:
    from app.main import app
    return app.state.dataset_service


def _get_plots_dir() -> pathlib.Path:
    from app.main import PLOTS_DIR
    return PLOTS_DIR


def _get_outlier_service(
    service: DatasetService = Depends(_get_dataset_service),
    plots_dir: pathlib.Path = Depends(_get_plots_dir),
) -> OutlierDetectionService:
    """Construct a fresh OutlierDetectionService per request (stateless)."""
    return OutlierDetectionService(
        dataset_service=service,
        plots_dir=plots_dir,
    )


# ---------------------------------------------------------------------------
# Endpoint 1 — Detect outliers (full analysis + chart)
# ---------------------------------------------------------------------------

@router.post(
    "/detect/{dataset_id}",
    response_model=SuccessResponse[OutlierDetectionReport],
    status_code=status.HTTP_200_OK,
    summary="Detect outliers in all numeric columns",
    description=(
        "Runs the chosen detection algorithm over every numeric column "
        "(or a caller-specified subset) and returns a structured JSON report "
        "plus a boxplot chart PNG.\n\n"
        "**Available methods:**\n"
        "- `iqr` — Tukey fences (Q1−k×IQR, Q3+k×IQR), distribution-free\n"
        "- `zscore` — standard or modified (MAD-based) Z-score\n"
        "- `isolation_forest` — tree-based ensemble, supports multivariate mode\n\n"
        "**JSON report includes:**\n"
        "- Per-column: outlier count, %, indices, values, bounds, stats\n"
        "- Dataset level: affected rows (unique), affected columns, total cells\n"
        "- Chart: path, download URL, dimensions, file size\n\n"
        "Use `GET /outliers/boxplots/{dataset_id}?method=iqr` to download the chart."
    ),
    responses={
        200: {"description": "Detection complete"},
        404: {"description": "Dataset not found"},
        422: {"description": "Invalid request parameters"},
    },
)
async def detect_outliers(
    dataset_id: str,
    request: OutlierDetectionRequest,
    svc: OutlierDetectionService = Depends(_get_outlier_service),
) -> SuccessResponse[OutlierDetectionReport]:
    """
    Run outlier detection on the specified dataset.

    Args:
        dataset_id: UUID of the dataset to analyse.
        request:    Request body with method, thresholds, column list, chart flag.
        svc:        Injected OutlierDetectionService.

    Returns:
        SuccessResponse wrapping OutlierDetectionReport.
    """
    logger.info(
        "Outlier detection request",
        dataset_id=dataset_id,
        method=request.method.value,
        generate_boxplots=request.generate_boxplots,
    )
    report = svc.detect(
        dataset_id=dataset_id,
        request=request,
        api_base_url="/api/v1",
    )
    return SuccessResponse(data=report)


# ---------------------------------------------------------------------------
# Endpoint 2 — Download boxplot PNG
# ---------------------------------------------------------------------------

@router.get(
    "/boxplots/{dataset_id}",
    summary="Download the boxplot chart as PNG",
    description=(
        "Returns the PNG boxplot grid generated by a previous call to "
        "`POST /outliers/detect/{dataset_id}`.  "
        "Pass the `method` query parameter to select which chart to retrieve "
        "(default: `iqr`).  Raises HTTP 404 if no chart exists for this dataset."
    ),
    responses={
        200: {"content": {"image/png": {}}, "description": "PNG chart"},
        404: {"description": "Chart not found — run detect first"},
    },
    response_class=FileResponse,
)
async def download_boxplots(
    dataset_id: str,
    method: OutlierMethod = Query(
        default=OutlierMethod.IQR,
        description="Detection method whose chart to retrieve",
    ),
    plots_dir: pathlib.Path = Depends(_get_plots_dir),
) -> FileResponse:
    """
    Stream the pre-generated boxplot PNG chart.

    Args:
        dataset_id: UUID of the dataset.
        method:     Detection method (iqr / zscore / isolation_forest).
        plots_dir:  Injected plots directory.

    Returns:
        FileResponse streaming the PNG.
    """
    filename   = f"outliers_{method.value}_{dataset_id}.png"
    chart_path = plots_dir / filename

    if not chart_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"No boxplot chart found for dataset '{dataset_id}' "
                f"using method '{method.value}'. "
                "Run POST /outliers/detect/{dataset_id} first."
            ),
        )

    return FileResponse(
        path=str(chart_path),
        media_type="image/png",
        filename=filename,
    )


# ---------------------------------------------------------------------------
# Endpoint 3 — List available detection methods
# ---------------------------------------------------------------------------

@router.get(
    "/methods",
    response_model=SuccessResponse[list[MethodCatalogEntry]],
    status_code=status.HTTP_200_OK,
    summary="List all registered outlier detection methods",
    description=(
        "Returns a catalogue of all registered detection strategies "
        "with their parameters, use cases, and known limitations.  "
        "No computation is performed."
    ),
)
async def list_methods(
    svc: OutlierDetectionService = Depends(_get_outlier_service),
) -> SuccessResponse[list[MethodCatalogEntry]]:
    """Return the method catalogue from the engine registry."""
    return SuccessResponse(data=svc.available_methods())


# ---------------------------------------------------------------------------
# Endpoint 4 — Compare all methods side-by-side
# ---------------------------------------------------------------------------

@router.post(
    "/compare/{dataset_id}",
    response_model=SuccessResponse[dict],
    status_code=status.HTTP_200_OK,
    summary="Run all detection methods and compare results",
    description=(
        "Runs IQR, Z-Score, and Isolation Forest on the same dataset "
        "and returns a side-by-side comparison.  Useful for understanding "
        "how sensitive each method is and which rows are consistently flagged "
        "across all three algorithms (consensus outliers).\n\n"
        "**Note:** boxplots are generated for each method separately."
    ),
    responses={
        200: {"description": "Comparison complete"},
        404: {"description": "Dataset not found"},
    },
)
async def compare_methods(
    dataset_id: str,
    columns: list[str] = Query(
        default=[],
        description="Columns to analyse (empty = all numeric)",
    ),
    generate_boxplots: bool = Query(
        default=False,
        description="Whether to generate boxplots for each method",
    ),
    svc: OutlierDetectionService = Depends(_get_outlier_service),
) -> SuccessResponse[dict]:
    """
    Run all three detection methods and compare their results.

    Returns a comparison dict with per-method summaries, consensus outliers
    (rows flagged by all methods), and union outliers (rows flagged by any).

    Args:
        dataset_id:        UUID of the dataset.
        columns:           Columns to analyse (empty = all numeric).
        generate_boxplots: Whether to build chart PNGs for each method.
        svc:               Injected OutlierDetectionService.

    Returns:
        SuccessResponse with comparison data.
    """
    logger.info("Outlier method comparison request", dataset_id=dataset_id)

    method_reports: dict[str, OutlierDetectionReport] = {}

    for method in [OutlierMethod.IQR, OutlierMethod.ZSCORE, OutlierMethod.ISOLATION_FOREST]:
        req = OutlierDetectionRequest(
            method=method,
            columns=columns,
            generate_boxplots=generate_boxplots,
        )
        try:
            method_reports[method.value] = svc.detect(
                dataset_id=dataset_id,
                request=req,
                api_base_url="/api/v1",
            )
        except Exception as exc:
            logger.warning(f"Method '{method.value}' failed in compare: {exc}")

    # Build consensus: rows flagged by ALL methods
    row_sets = [
        set(r.affected_row_indices)
        for r in method_reports.values()
        if r.affected_row_indices
    ]
    consensus_rows = sorted(set.intersection(*row_sets)) if len(row_sets) == 3 else []
    union_rows     = sorted(set.union(*row_sets)) if row_sets else []

    comparison = {
        "dataset_id": dataset_id,
        "methods": {
            name: {
                "total_outlier_rows":  rep.total_outlier_rows,
                "total_outlier_cells": rep.total_outlier_cells,
                "affected_columns":    rep.affected_columns,
                "elapsed_ms":          rep.elapsed_ms,
                "chart_url":           rep.chart.chart_url if rep.chart else None,
            }
            for name, rep in method_reports.items()
        },
        "consensus_outlier_rows":          consensus_rows,
        "consensus_outlier_count":         len(consensus_rows),
        "union_outlier_rows":              union_rows[:50],   # cap at 50 in response
        "union_outlier_count":             len(union_rows),
        "agreement_note": (
            f"{len(consensus_rows)} row(s) flagged by all 3 methods (high-confidence outliers). "
            f"{len(union_rows)} unique row(s) flagged by at least one method."
        ),
    }

    return SuccessResponse(data=comparison)
